name: riverpod_stateful_service
description: >
  This package provides a lightweight stateful_service wrapper for Riverpod.
  
  See the stateful_service package for more information.
version: 5.0.4
homepage: https://github.com/tjarvstrand/stateful_service

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  riverpod: ^2.6.1
  stateful_service: ^5.0.4

dev_dependencies:
  flutter_lints:

