name: riverpod_stateful_service
description: >
  This package provides a lightweight stateful_service wrapper for Riverpod.
  
  See the stateful_service package for more information.
version: 6.2.0
homepage: https://github.com/tjarvstrand/stateful_service

environment:
  sdk: ">=3.5.0 <4.0.0"

resolution: workspace

dependencies:
  riverpod: ^2.6.1
  stateful_service: ^6.2.0

dev_dependencies:
  flutter_lints:

