name: riverpod_stateful_service
description: >
  This package provides a lightweight stateful_service wrapper for Riverpod.
  
  See the stateful_service package for more information.
version: 7.0.0
homepage: https://github.com/tjarvstrand/stateful_service

environment:
  sdk: ">=3.5.0 <4.0.0"

resolution: workspace

dependencies:
  meta: ^1.16.0
  riverpod: ^3.0.0
  stateful_service: ^7.0.0

dev_dependencies:
  flutter_lints: any

