name: riverpod_stateful_service_example
description: >
  Example use of riverpod stateful service
version: 1.0.0+2
homepage: https://github.com/tjarvstrand/stateful_service
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.35.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  riverpod: ^3.0.0
  riverpod_stateful_service: any
  stateful_service: any

dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter