name: shared_preferences_stateful_service_cache
description: >
  A shared_preferences-based cache implementation for stateful_service.

  See the stateful_service package for more information.

version: 5.0.2
homepage: https://github.com/tjarvstrand/stateful_service

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  meta: ^1.11.0
  shared_preferences: ^2.3.3
  stateful_service: ^5.0.2

dev_dependencies:
  flutter_lints:
  test:
