name: shared_preferences_stateful_service_cache
description: "A shared_preferences-based cache for stateful_service."
version: 1.0.0
homepage: https://github.com/tjarvstrand/stateful_service

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  meta: ^1.15.0
  shared_preferences: ^2.2.3
  stateful_service: 1.0.0

dev_dependencies:
  flutter_lints:
  test:
