name: riverpod_stateful_service_annotation
description: >
  This package provides annotations to be used together with riverpod_stateful_service_generator to 
  generate stateful service providers for Riverpod.
  
  See the stateful_service package for more information.
version: 6.2.0+2
homepage: https://github.com/tjarvstrand/stateful_service

environment:
  sdk: ">=3.5.0 <4.0.0"

resolution: workspace

dependencies:
  meta: ^1.11.0
  riverpod_annotation: ^3.0.0-dev.17
  riverpod_stateful_service: ^6.2.0+2
  stateful_service: ^6.2.0+2

dev_dependencies:
  flutter_lints:

