name: riverpod_stateful_service_annotation
description: >
  This package provides annotations to be used together with riverpod_stateful_service_generator to 
  generate stateful service providers for Riverpod.
  
  See the stateful_service package for more information.
version: 2.0.1
homepage: https://github.com/tjarvstrand/stateful_service

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.15.0
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  stateful_service: ^2.0.0

dev_dependencies:
  flutter_lints:

