name: riverpod_stateful_service_generator_example
description: >
  Example use of riverpod stateful service generator
version: 1.0.0+2
homepage: https://github.com/tjarvstrand/stateful_service
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0-dev.17
  riverpod: ^3.0.0-dev.17
  riverpod_annotation: ^3.0.0-dev.17
  riverpod_stateful_service: any
  riverpod_stateful_service_annotation: any

dev_dependencies:
  build_runner: ^2.7.0
  flutter_lints: any
  riverpod_generator: ^3.0.0-dev.17
  riverpod_stateful_service_generator: any

dependency_overrides:
  riverpod_stateful_service:
    path: ../../riverpod_stateful_service
  riverpod_stateful_service_annotation:
    path: ../../riverpod_stateful_service_annotation
  riverpod_stateful_service_generator:
    path: ..