name: riverpod_stateful_service_generator
description: >
  This package provides a lightweight stateful_service wrapper for Riverpod using code generation.
  
  See the stateful_service package for more information.
version: 5.0.2
homepage: https://github.com/tjarvstrand/stateful_service

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^6.7.0
  build: ^2.4.1
  build_config: ^1.1.1
  collection: ^1.18.0
  dart_style: ^2.3.7
  meta: ^1.11.0
  path: ^1.9.0
  riverpod_annotation: ^2.6.1
  riverpod_stateful_service_annotation: ^5.0.2
  source_gen: ^1.5.0

dev_dependencies:
  build_test: ^2.2.2
  flutter_lints:
  riverpod: ^2.6.1
  riverpod_generator: ^2.6.2
  stateful_service: ^5.0.2
  test: ^1.25.7

