name: riverpod_stateful_service_generator
description: >
  This package provides a lightweight stateful_service wrapper for Riverpod using code generation.
  
  See the stateful_service package for more information.
version: 6.0.0
homepage: https://github.com/tjarvstrand/stateful_service

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^7.0.0
  build: ^2.4.1
  build_config: ^1.1.1
  collection: ^1.18.0
  meta: ^1.11.0
  path: ^1.9.0
  riverpod_annotation: ^2.6.1
  riverpod_stateful_service_annotation: ^6.0.0
  source_gen: ^2.0.0

dev_dependencies:
  build_test: ^2.2.2
  dart_style: ^3.0.1
  flutter_lints:
  pub_semver: ^2.2.0
  riverpod: ^2.6.1
  riverpod_generator: ^2.6.5
  stateful_service: ^6.0.0
  test: ^1.25.7

