name: riverpod_stateful_service_generator
description: >
  This package provides a lightweight stateful_service wrapper for Riverpod using code generation.
  
  See the stateful_service package for more information.
version: 7.0.1
homepage: https://github.com/tjarvstrand/stateful_service

environment:
  sdk: ">=3.5.0 <4.0.0"

resolution: workspace

dependencies:
  analyzer: ^7.0.0
  build: ^3.0.0
  build_config: ^1.1.1
  built_collection: ^5.1.1
  code_builder: ^4.11.0
  collection: ^1.18.0
  dart_style: ^3.1.0
  meta: ^1.11.0
  path: ^1.9.0
  riverpod_stateful_service_annotation: ^7.0.1
  source_gen: ^3.0.0

dev_dependencies:
  build_runner_core: ^9.1.2
  build_test: ^3.2.1
  flutter_lints:
  pub_semver: ^2.2.0
  riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0
  riverpod_generator: ^3.0.0
  stateful_service: ^7.0.1
  test: ^1.25.7

