name: stateful_service

on:
  push:
    branches:
     - main
     - ci-*
  pull_request:

jobs:
  test:
    name: Test stateful_service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/stateful_service
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: flutter pub get
      - run: dart format --set-exit-if-changed  --output=none .
      - run: flutter test


